name: Clash Monitor

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:

      # ======================================================
      # 1. Baixar arquivos
      # ======================================================

      - name: Baixar arquivos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ======================================================
      # 2. Configurar Python
      # ======================================================

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ======================================================
      # 3. Instalar dependências
      # ======================================================

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # ======================================================
      # 4. Executar monitor
      # ======================================================

      - name: Executar monitor
        env:
          CR_API_KEY: ${{ secrets.CR_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python monitor.py

      # ======================================================
      # 5. Salvar última batalha
      # ======================================================

      - name: Salvar última batalha
        run: |

          if git diff --quiet -- last_battle.txt; then
            echo "Nenhuma nova batalha foi detectada."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add last_battle.txt

          git commit -m "Atualizar última batalha monitorada"

          git push
